module.exports = {
    ALPHABET: [
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
    ],
    ALLOWED_FOLDERS: ["userOne, userTwo"],
    DAYS_OF_THE_WEEK: ["monday", "tuesday", "wednsday", "thursday", "friday", "saturday", "sunday"],
    DAYS_OF_THE_WEEK_ABBREVIATED: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    ADD_VARIABLE: "Add variable",
    BOOLEAN: "boolean",
    CHANGE_FIELD: "Change field",
    SUCCESS: "Success",
    USER_DATA_STORAGE: "./userDataStorage/",
    ERROR: "Error",
    EMPTY_FIELD: "Empty field(s):",
    READ_EXCEL: "Read Excel",
    RUN_ERROR: "Error during procedure execution",
    Role_NOT_FOUND: "Roles not found",
    COPY_EXCEL: "Copy Excel",
    STRING: "string",
    SINGLE: "Single",
    NUMBER: "number",
    NAME: "name",
    READ_FROM_FTP: "Read from FTP",
    TRAINEE: "trainee",
    INVALID_USER_ACTION: "Invalid user action",
    MAIL_EXCEL: "Mail Excel",
    MAIL_TEXT: "Mail Text",
    USER_NOT_FOUND: "User not found",
    NO_PROCEDURE_FOUND: "No procedures found",
    REGISTRATION_ERROR: "Registration error",
    FROM: "from",
};
