module.exports = {
    ALPHABET: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"],
    ADD_VARIABLE: "Add variable",
    BOOLEAN: "boolean",
    CHANGE_FIELD: "Change field",
    SUCCESS: "Success",
    USER_DATA_STORAGE: "./userDataStorage/",
    ERROR: "Error",
    READ_EXCEL: "Read Excel",
    RUN_ERROR: "Error during procedure execution",
    COPY_EXCEL: "Copy Excel",
    STRING: "string",
    NUMBER: "number",
    READ_FROM_FTP: "Read from FTP",
    TRAINEE: "trainee",
    MAIL_EXCEL: "Mail Excel",
    MAIL_TEXT: "Mail Text",
    USER_NOT_FOUND: "User not found",
    NO_PROCEDURE_FOUND: "No procedures found"
};
